#!/usr/bin/env bash

set -o errexit -o pipefail

main() {
    init

    #@ -h,--help | print this text
    #@ list | Print installed packages
    list::installed "$@"
}

list::installed() {
    local name="$1"

    for n in "${RAFI_INDEX_INSTALLED_DIR}/${name:-.}/"*; do
	printf '%s\n' "${n##*/}"
    done
}

main "$@"
