#!/usr/bin/env bash

set -o errexit -o pipefail

main() {
    init

    #@ -h,--help | Print this text
    #@ location | Print package install path

    if [[ -z "$1" ]]; then
	log::fatal "No package specified."
    fi

    location::print "$@"
}

# TODO: support declaring the version
location::print() {
    local name="${1:?}"

    local install_dir="${RAFI_USR_DATA_DIR:?}/${name}"
    if [[ ! -d "$install_dir" ]]; then
	log::fatal "Package '$name' not found."
    fi

    if [[ ! -h "${RAFIX_INDEX_EQUIPPED_DIR}/${name}" ]]; then
	log::debug "Path '${RAFIX_INDEX_EQUIPPED_DIR}/${name}' does not exist."
	log::fatal "No version set for package '$name'. Is it even installed?"
    fi
    
    local res
    res="$(readlink -f "${RAFIX_INDEX_EQUIPPED_DIR}/${name}")"

    printf '%s\n' "$res"
}

main "$@"
