#!/usr/bin/env bash

set -o errexit -o pipefail

main() {
    init

    #@ -h,--help | print this text

    #@ ping | returns pong



    #fs::walk_dir_reverse "$1" "$2" echo
    fs::walk_dir "$1" yeet
}

yeet() {

    
    
    echo YEET "$*"
}



main "$@"
