#!/usr/bin/env bash

set -o errexit -o pipefail

main() {
    init

    #@ -h,--help | Print this text
    #@ version | Print package version

    if [[ -z "$1" ]]; then
	printf '%s\n' "$(<VERSION)"
	exit 0
    fi
    
    version::print "$@"
}

version::print() {
    local name="${1:?}"

    # TODO: we could error out sooner if we check if the package dir exists
    if [[ ! -h "${RAFI_INDEX_EQUIPPED_VERSION}/${name}" ]]; then
	log::debug "Path '${RAFI_INDEX_EQUIPPED_VERSION}/${name}"
	log::fatal "No version set for package '$name'. Is it even installed?"
    fi

    local res
    res="$(readlink -f "${RAFI_INDEX_EQUIPPED_VERSION}/${name}")"

    printf '%s\n' "${res##*/}"
}

main "$@"
